!INTERFILE  :=
!imaging modality := NM
name of data file := earl_tc99m_dew.s
originating system := 
!version of keys := 3.3
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := Tomographic
imagedata byte order := LITTLEENDIAN
number of radionuclides := 1
!SPECT STUDY (General) :=
!number format := float
!number of bytes per pixel := 4
!number of projections := 120
!extent of rotation := 360
process status := acquired
!SPECT STUDY (acquired data):=
!direction of rotation := CW
start angle := 180
orbit := Circular
Radius := 203.842
!matrix size [1] := 256
!scaling factor (mm/pixel) [1] := 2.20774
!matrix size [2] := 256
!scaling factor (mm/pixel) [2] := 2.20774
!END OF INTERFILE :=
